### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by adrianomelo** [developandplay/material-components-web-miso#3]
Hello there,

Thanks for starting this project! :+1: 

I like the approach to reuse the JS and API from the Elm library. I have used the Elm library in the past, and it works fine.

I am working on a side-project, and, ideally, I would like to use Material Design. I can contribute to this project with some of the missing components if you don't mind.

I started porting the Select component. Did you start working on it already?

Also, it would be great to publish the project as a library. Do you have plans to publishing it?

**Comment by troibe** [comment]
Hi Adriano,
Happy to hear that you are interested in helping out!
Yes I'm still working on the project and I also plan to publish it by the end of the year.
I have not started working on the select component yet so it sounds like a good entry point.
If you are also contributing I will upload a script that helps with some common replacements. It's far from perfect but helps you with a lot of annoying stuff.
Looking forward to collaborating.
Though I have to say I probably will be a bit sporadic when contributing code myself. For the next 1.5 months I'm still doing an internship. However I'm happy to assist, review and approve anytime.

**Comment by troibe** [comment]
This is the script that I was using https://github.com/developandplay/elm-to-miso. Feel free to adjust and extend it!

**Comment by adrianomelo** [comment]
Hey @developandplay,

Sounds good! I was wondering better ways of porting the package. The script will surely help a lot. I already gave it a try, and it is a good start.

I made some small changes to the script. I will start creating some PRs on both projects.

PS: Given that it is October, do you mind adding the label "hacktoberfest-accepted" to the PRs, or maybe adding "hacktoberfest" to both projects?

**Comment by troibe** [comment]
Added hacktoberfest to both! Sounds like a great initiative.

**Comment by adrianomelo** [comment]
I am going to close this issue given that we introduced a basic version of Select component.
