### ISSUE TITLE
Elements not clickable

### ISSUE THREAD

**Issue by deemp** [developandplay/material-components-web-miso#39]
When I run with `nix-shell --run reload` and open `http://localhost:8081/` (should not be 8080 in the [description](https://github.com/developandplay/material-components-web-miso/tree/master/sample-app-jsaddle#dev), btw), I can't click on any element in Firefox.

**Comment by deemp** [comment]
Please help, @developandplay

**Comment by troibe** [comment]
Hi Danila,
I'm happy to hear you are interested in using the web components. (If there
is more interest I might consider publishing it on hackage)...

Feel free to open a pull request to change the port to 8080 or change the
readme.

Could you try opening it with a chromium based browser? I remember that
there were some interactivity issues on Firefox with jsaddle (which is used
for development).

Alternatively you can make the release version which definitely works on
Firefox (as you can see on the demo website).

Best wishes
Martin


Danila Danko ***@***.***> schrieb am Sa., 15. Jan. 2022,
13:46:

**Comment by deemp** [comment]
Thank you, Martin! I was searching for a working Miso + JSaddle example, and yours was sehr schön. I didn't expect that you answer soon, so I found out that this browser constraint was also [pointed](https://github.com/fourmolu/fourmolu/tree/master/ormolu-live#local-development-with-jsaddle) here. In Chrome, it works just fine.
